#ifndef LED_MATRIX_CONFIG_H_
#define LED_MATRIX_CONFIG_H_


#define LED_MATRIX_ROWS_PINS		{{GPIO_PORTA, GPIO_PIN0, GPIO_OUTPUT, GPIO_PUSH_PULL, GPIO_MIDIUM, GPIO_NO_PULL, GPIO_AF0},\
									{GPIO_PORTB, GPIO_PIN2, GPIO_OUTPUT, GPIO_PUSH_PULL, GPIO_MIDIUM, GPIO_NO_PULL, GPIO_AF0},\
									{GPIO_PORTB, GPIO_PIN4, GPIO_OUTPUT, GPIO_PUSH_PULL, GPIO_MIDIUM, GPIO_NO_PULL, GPIO_AF0},\
									{GPIO_PORTA, GPIO_PIN3, GPIO_OUTPUT, GPIO_PUSH_PULL, GPIO_MIDIUM, GPIO_NO_PULL, GPIO_AF0},\
									{GPIO_PORTA, GPIO_PIN4, GPIO_OUTPUT, GPIO_PUSH_PULL, GPIO_MIDIUM, GPIO_NO_PULL, GPIO_AF0},\
									{GPIO_PORTB, GPIO_PIN5, GPIO_OUTPUT, GPIO_PUSH_PULL, GPIO_MIDIUM, GPIO_NO_PULL, GPIO_AF0},\
									{GPIO_PORTA, GPIO_PIN6, GPIO_OUTPUT, GPIO_PUSH_PULL, GPIO_MIDIUM, GPIO_NO_PULL, GPIO_AF0},\
									{GPIO_PORTB, GPIO_PIN6, GPIO_OUTPUT, GPIO_PUSH_PULL, GPIO_MIDIUM, GPIO_NO_PULL, GPIO_AF0}}


#define LED_MATRIX_COLUMNS_PINS		{{GPIO_PORTB, GPIO_PIN8, GPIO_OUTPUT, GPIO_PUSH_PULL, GPIO_MIDIUM, GPIO_NO_PULL, GPIO_AF0},\
									{GPIO_PORTB, GPIO_PIN9, GPIO_OUTPUT, GPIO_PUSH_PULL, GPIO_MIDIUM, GPIO_NO_PULL, GPIO_AF0},\
									{GPIO_PORTB, GPIO_PIN10, GPIO_OUTPUT, GPIO_PUSH_PULL, GPIO_MIDIUM, GPIO_NO_PULL, GPIO_AF0},\
									{GPIO_PORTB, GPIO_PIN12, GPIO_OUTPUT, GPIO_PUSH_PULL, GPIO_MIDIUM, GPIO_NO_PULL, GPIO_AF0},\
									{GPIO_PORTB, GPIO_PIN13, GPIO_OUTPUT, GPIO_PUSH_PULL, GPIO_MIDIUM, GPIO_NO_PULL, GPIO_AF0},\
									{GPIO_PORTB, GPIO_PIN14, GPIO_OUTPUT, GPIO_PUSH_PULL, GPIO_MIDIUM, GPIO_NO_PULL, GPIO_AF0},\
									{GPIO_PORTB, GPIO_PIN15, GPIO_OUTPUT, GPIO_PUSH_PULL, GPIO_MIDIUM, GPIO_NO_PULL, GPIO_AF0},\
									{GPIO_PORTA, GPIO_PIN8, GPIO_OUTPUT, GPIO_PUSH_PULL, GPIO_MIDIUM, GPIO_NO_PULL, GPIO_AF0}}


#endif




